### ISSUE TITLE
[FEATURE] To add autocomplete Searching for notes

### ISSUE THREAD

**Issue by KavyanshYadav** [ramxcodes/notes-buddy#5]
![chrome-capture-2024-12-28](https://github.com/user-attachments/assets/073434e7-e999-4537-af2c-5c1fc1e927e3)

**Comment by KavyanshYadav** [comment]
ui and functionality can be futher imporve

**Comment by ramxcodes** [comment]
i've Assigned the issue to you, Make sure the search functionality should not have high performance impact !
also do check for build time errors!
